sonar.projectKey=pfa-management-Frontend
sonar.projectName=pfa-management-Frontend
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.exclusions=node_modules/**,coverage/**,tests/**
sonar.tests=test
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=server.js,node_modules/**
sonar.login=sqp_cff06b598e421b9b4a474a41878c81ee9cda247c
