sonar.projectKey=pfa-management-backend
sonar.projectName=pfa-management-backend
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.exclusions=node_modules/**,coverage/**,tests/**,Dockerfile
sonar.tests=test
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=server.js,node_modules/**,Dockerfile
sonar.login=sqp_d3d22ac7cd540057f10257444cb3a88e8a002918
sonar.javascript.lcov.reportPaths=coverage/lcov.info